<script src="http://cdn.onesignal.com/sdks/OneSignalSDK.js" async></script>
<script>
    var OneSignal = window.OneSignal || [];
    var initConfig = {
        appId: "4beb1622-1cff-41c5-a84a-af6b8420d79b",
        notifyButton: {
            enable: true,
        },
        allowLocalhostAsSecureOrigin: true,
    };
    OneSignal.push(function () {
        OneSignal.SERVICE_WORKER_PARAM = {scope: '/tasks/'};
        OneSignal.SERVICE_WORKER_PATH = 'tasks/OneSignalSDKWorker.js'
        OneSignal.SERVICE_WORKER_UPDATER_PATH = 'tasks/OneSignalSDKUpdaterWorker.js'
        OneSignal.init(initConfig);
    });
</script>
<script>
    var config = {
        url: "{{url('')}}",
        admin_url: " {{ url('apanel')}}",
        seller_url: " {{ url('seller-center')}}",
        seller_ajax_url: " {{ url('seller-center/ajax')}}",
        upload_url: "{{url('apanel/ajax/upload') }}",
        delete_upload_url: "{{url('apanel/ajax/upload') }}",
        ajax_url: " {{ url('apanel/ajax')}}",
        public_path: " {{ url('public//')}}",
        img_path: " {{ admin_img('')}}",
        upload_path: " {{ url('public/uploads')}}",
        lang_code: "{{$lang_code}}",
        pusher_app_id: "{{env('PUSHER_APP_ID')}}",
        pusher_app_key: "{{env('PUSHER_APP_KEY')}}",
        pusher_cluster: "{{env('PUSHER_APP_CLUSTER')}}",
        pusher_encrypted: true,
        one_signal_app_id: "{{env('ONE_SIGNAL_APP_ID')}}",
        user_id: '{{$User?$User->id:false}}',
        locales: '{!!json_encode($locales)!!}',
        currency: '{{currency()}}',
        user_type_admin: '{{config("constants.users.admin_type")}}',
        user_type_individual: '{{config("constants.users.individual_type")}}',
        prm: '{!! $User ? json_encode($User->permissions) :json_encode([]) !!}',

    }
    var lang = {
        add_a_card: "{{ t('add_a_card')}}",

        no_category_selected: "{{ t('no_category_selected')}}",
        name: "{{ t('name')}}",
        sub_menu: "{{ t('sub_menu')}}",
        add_sub_menu: "{{ t('add_sub_menu')}}",
        assign: "{{ t('assign')}}",
        accept: "{{ t('accept')}}",
        reject: "{{ t('reject')}}",
        processing: "{{ t('processing')}}",
        on_shipping: "{{ t('on_shipping')}}",
        delivered: "{{ t('delivered')}}",
        catgegory_selected_successfully: "{{ t('catgegory_selected_successfully')}}",
        add_to_category: "{{ t('add_to_category')}}",
        options: "{{ t('options')}}",
        items: "{{ t('items')}}",
        new_item: "{{ t('new_item')}}",
        price: "{{ t('price')}}",
        choices: "{{ t('choices')}}",
        items_listing: "{{ t('items_listing')}}",
        add_category: "{{ t('add_category')}}",
        new_bill: "{{ t('new_bill')}}",
        next: "{{ t('next')}}",
        add_payment: "{{ t('add_payment')}}",
        view_payments: "{{ t('view_payments')}}",
        completed: "{{ t('completed')}}",
        canceled: "{{ t('canceled')}}",
        not_completed: "{{ t('not_completed')}}",
        tooth_treatment: "{{ t('tooth_treatment')}}",
        not_attend: "{{ t('not_attend')}}",
        confirm: "{{ t('confirm')}}",
        cancel: "{{ t('cancel')}}",
        attend: "{{ t('attend')}}",
        inside: "{{ t('inside')}}",
        outside_and_wait: "{{ t('outside_and_wait')}}",
        finish: "{{ t('finish')}}",
        add_card: "{{ t('add_card')}}",
        appointments_listing: "{{ t('appointments_listing')}}",
        available_times: "{{ t('available_times')}}",
        finished: "{{ t('finished')}}",
        request_has_been_sent: "{{ t('request_has_been_sent')}}",
        item: "{{ t('item')}}",
        inventory_on_hand: "{{ t('inventory_on_hand')}}",
        accounts: "{{ t('accounts')}}",
        by: "{{ t('by')}}",
        rooms: "{{ t('rooms')}}",
        safes: "{{ t('safes')}}",
        duration: "{{ t('duration')}}",
        cancel: "{{ t('cancel')}}",
        activities: "{{ t('activities')}}",
        shift: "{{ t('shift')}}",
        course: "{{ t('course')}}",
        level: "{{ t('level')}}",
        branch: "{{ t('branch')}}",
        room: "{{ t('room')}}",
        day_pattern: "{{ t('day_pattern')}}",
        time_slot: "{{ t('time_slot')}}",
        student: "{{ t('student')}}",
        status: "{{ t('status')}}",
        from: "{{ t('from')}}",
        to: "{{ t('to')}}",
        note: "{{ t('note')}}",
        created_at: "{{ t('created_at')}}",
        employee: "{{ t('employee')}}",
        group_title: "{{ t('group_title')}}",
        title: "{{ t('title')}}",
        view: "{{ t('view')}}",
        feedback: "{{ t('feedback')}}",
        confirmed: "{{ t('confirmed')}}",
        edit_session: "{{ t('edit_session')}}",
        please_enter_bill_no: "{{ t('please_enter_bill_no')}}",
        remove: "{{ t('remove')}}",
        confirm: "{{ t('confirm')}}",
        name_en: "{{ t('name_en')}}",
        name_ar: "{{ t('name_ar')}}",
        items: "{{ t('name')}}",
        email: "{{ t('email')}}",
        address: "{{ t('address')}}",
        phone: "{{ t('phone')}}",
        items: "{{ t('items')}}",
        courses: "{{ t('courses')}}",
        other: "{{ t('other')}}",
        no_item_is_selected: "{{ t('no_item_is_selected')}}",
        item_is_selected_before: "{{ t('item_is_selected_before')}}",
        apply: "{{ t('apply')}}",
        attendance_done_successfully: "{{ t('attendance_done_successfully')}}",
        no_results: "{{ t('no_results')}}",
        no_student_selected: "{{ t('no_student_selected')}}",
        student_is_selected_before: "{{ t('student_is_selected_before')}}",
        search: "{{ t('search')}}",
        images: "{{ t('images')}}",
        set_as_default: "{{ t('set_as_default')}}",
        you_can_upload_images_with_max_size_1MP: "{{ t('you_can_upload_images_with_max_size_1MP')}}",
        category_is_selected_before: "{{ t('category_is_selected_before')}}",
        confirm_message: "{{ t('are_you_sure_?')}}",
        attention_message: "{{ t('attention_message')}}",
        not_special: "{{ t('not_special')}}",
        special: "{{ t('special')}}",
        filesize_can_not_be_more_than: "{{ t('filesize_can_not_be_more_than')}}",
        gender: "{{ t('gender')}}",
        male: "{{ t('male')}}",
        female: "{{ t('female')}}",
        import: "{{ t('import')}}",
        add: "{{ t('add')}}",
        edit: "{{ t('edit')}}",
        save: "{{ t('save')}}",
        notify: "{{ t('notify')}}",
        remove: "{{ t('remove')}}",
        choose: "{{ t('choose')}}",
        delete: "{{ t('delete')}}",
        message: "{{ t('message')}}",
        send: "{{ t('send')}}",
        no_results: "{{ t('no_results')}}",
        no_category_selected: "{{ t('no_category_selected')}}",
        active: "{{ t('active')}}",
        not_active: "{{ t('not_active')}}",
        close: "{{ t('close')}}",
        no_item_selected: "{{ t('no_item_selected')}}",
        save: "{{ t('save')}}",
        updated_successfully: "{{ t('updated_successfully')}}",
        loading: "{{ t('loading')}}",
        deleting: "{{ t('deleting')}}",
        delete: "{{ t('delete')}}",
        uploading: "{{ t('uploading')}}",
        upload: "{{ t('upload')}}",
        required: "{{ t('this_field_is_required')}}",
        email_not_valid: "{{ t('email_is_not_valid')}}",
        alert_message: "{{ t('alert_message')}}",
        confirm_message_title: "{{ t('are you sure !?')}}",
        deleting_cancelled: "{{ t('deleting_cancelled')}}",
        yes: "{{ t('yes')}}",
        no: "{{ t('no')}}",
        error: "{{ t('error')}}",
        try_again: "{{ t('try_again')}}",
        choose_one: "{{ t('please_choose_one')}}",
        no_file_to_upload: "{{ t('no_file_to_upload')}}",
        //new

    };
    var errorElements = new Array;
    var new_attachment = new Array;
    var old_attachment = new Array;
</script>